CREATE DATABASE GUSTAVOFERREIRADASILVA;
USE GUSTAVOFERREIRADASILVA;

CREATE TABLE Autores (
CodAutor INT AUTO_INCREMENT PRIMARY KEY,
Autor VARCHAR (100) NOT NULL);

CREATE TABLE Editoras (
CodEditora INT AUTO_INCREMENT PRIMARY KEY,
Editora VARCHAR (100) NOT NULL);

CREATE TABLE Generos (
CodGenero INT PRIMARY KEY,
Genero VARCHAR (100) NOT NULL);

CREATE TABLE Livros(
CodLivro INT AUTO_INCREMENT PRIMARY KEY,
ISBN INT NOT NULL,
Titulo VARCHAR (100) NOT NULL,
CodAutor INT, 
CodEditora INT,
CodGenero INT,
Ano YEAR NOT NULL,
Paginas INT NOT NULL,
CONSTRAINT FKCODAUTORLIVROS FOREIGN KEY (CodAutor) REFERENCES Autores(CodAutor),
CONSTRAINT FKCODEDITORALIVROS FOREIGN KEY (CodEditora) REFERENCES Editoras(CodEditora),
CONSTRAINT FKCODGENERO FOREIGN KEY (CodGenero) REFERENCES Generos(CodGenero));
 

