/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.views;

import br.edu.utfpr.DAO.AutoresDAO;
import br.edu.utfpr.DAO.EditorasDAO;
import br.edu.utfpr.DAO.GenerosDAO;
import br.edu.utfpr.DAO.LivrosDAO;
import br.edu.utfpr.Entidades.Autores;
import br.edu.utfpr.Entidades.Editoras;
import br.edu.utfpr.Entidades.Generos;
import br.edu.utfpr.Entidades.Livros;
import br.edu.utfpr.Models.LivrosTableModel;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author gustavo
 */
public class DlgLivros extends javax.swing.JDialog {

    private final LivrosTableModel livrosTableModel;
    private int linhaSelecionada;

    public DlgLivros(java.awt.Frame parent, boolean modal, LivrosTableModel livrosTableModel) {
        super(parent, modal);
        initComponents();
        GenerosDAO generosDao = new GenerosDAO();
        AutoresDAO autoresDao = new AutoresDAO();
        EditorasDAO editorasDao = new EditorasDAO();
        cbGenero.setModel(new DefaultComboBoxModel<>(new Vector<>(generosDao.getGeneros())));
        cbAutor.setModel(new DefaultComboBoxModel<>(new Vector<>(autoresDao.getAutores())));
        cbEditora.setModel(new DefaultComboBoxModel<>(new Vector<>(editorasDao.getEditoras())));
        this.livrosTableModel = livrosTableModel;

    }

    DlgLivros(Object object, boolean b, LivrosTableModel livrosTableModel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public DlgLivros(Object object, boolean b, LivrosTableModel livrosTableModel, int codLivro, int linhaSelecionada) {
//        super(parent, modal);
        initComponents();
        this.livrosTableModel = livrosTableModel;
        Livros livros = new Livros();
        LivrosDAO livrosDao = new LivrosDAO();
        GenerosDAO generosDao = new GenerosDAO();
        AutoresDAO autoresDao = new AutoresDAO();
        EditorasDAO editorasDao = new EditorasDAO();
        cbGenero.setModel(new DefaultComboBoxModel<>(new Vector<>(generosDao.getGeneros())));
        cbAutor.setModel(new DefaultComboBoxModel<>(new Vector<>(autoresDao.getAutores())));
        cbEditora.setModel(new DefaultComboBoxModel<>(new Vector<>(editorasDao.getEditoras())));
        livros = livrosDao.getLivrosById(codLivro);

        tfCodLivro.setText(Integer.toString(livros.getCodLivro()));
        tfTitulo.setText(livros.getTitulo());
        this.linhaSelecionada = linhaSelecionada;

    }

    private Livros pesquisar(Livros livros) {
        LivrosDAO livrosDao = new LivrosDAO();
        return livrosDao.getLivrosByNome(livros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelCb = new javax.swing.JPanel();
        lbGenero = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        lbEditora = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        cbAutor = new javax.swing.JComboBox<>();
        cbEditora = new javax.swing.JComboBox<>();
        panelBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        panelTf = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        lbISBN = new javax.swing.JLabel();
        tfISBN = new javax.swing.JTextField();
        lbAno = new javax.swing.JLabel();
        tfAno = new javax.swing.JTextField();
        lbPaginas = new javax.swing.JLabel();
        tfPaginas = new javax.swing.JTextField();
        tfCodLivro = new javax.swing.JTextField();
        lbCodLivro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbGenero.setText("Gênero");

        lbAutor.setText("Autor");

        lbEditora.setText("Editora");

        javax.swing.GroupLayout panelCbLayout = new javax.swing.GroupLayout(panelCb);
        panelCb.setLayout(panelCbLayout);
        panelCbLayout.setHorizontalGroup(
            panelCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCbLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAutor)
                .addGap(10, 10, 10)
                .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEditora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEditora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCbLayout.setVerticalGroup(
            panelCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCbLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenero)
                    .addComponent(lbAutor)
                    .addComponent(lbEditora)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/Hardware-Floppy-icon (Custom).png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/Log-Out-icon (Custom).png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnSalvar)
                .addGap(96, 96, 96)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitulo.setText("Título");

        lbISBN.setText("ISBN");

        lbAno.setText("Ano");

        lbPaginas.setText("Páginas");

        tfCodLivro.setEditable(false);

        lbCodLivro.setText("Código");

        javax.swing.GroupLayout panelTfLayout = new javax.swing.GroupLayout(panelTf);
        panelTf.setLayout(panelTfLayout);
        panelTfLayout.setHorizontalGroup(
            panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo)
                    .addComponent(lbAno)
                    .addComponent(lbCodLivro))
                .addGap(21, 21, 21)
                .addGroup(panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCodLivro)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(tfAno))
                .addGap(54, 54, 54)
                .addGroup(panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTfLayout.createSequentialGroup()
                        .addComponent(lbISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTfLayout.createSequentialGroup()
                        .addComponent(lbPaginas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTfLayout.setVerticalGroup(
            panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbISBN)))
                .addGap(18, 18, 18)
                .addGroup(panelTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAno)
                    .addComponent(tfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPaginas))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(panelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Livros livros = new Livros();
        LivrosDAO livrosDao = new LivrosDAO();
        livros.setTitulo(tfTitulo.getText());
        livros.setIsbn(Double.parseDouble(tfISBN.getText()));
        livros.setAno(Short.valueOf(tfAno.getText()));
        livros.setPaginas(Integer.parseInt(tfPaginas.getText()));
        livros.setGenerosEntity((Generos) cbGenero.getSelectedItem());
        livros.setAutoresEntity((Autores) cbAutor.getSelectedItem());
        livros.setEditorasEntity((Editoras) cbEditora.getSelectedItem());
        if (tfCodLivro.getText().isEmpty()) {
            livrosDao.inserir(livros);
            livrosTableModel.addLivro(pesquisar(livros));
        } else {
            livros.setCodLivro(Integer.parseInt(tfCodLivro.getText()));
            livrosDao.atualizar(livros);
            livrosTableModel.updateLivros(linhaSelecionada, livros);
        }

        this.setVisible(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                DlgLivros dialog = new DlgLivros(new javax.swing.JFrame(), true);
////                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
////                    @Override
////                    public void windowClosing(java.awt.event.WindowEvent e) {
////                        System.exit(0);
////                    }
////                });
////                dialog.setVisible(true);
////            }
////        });
////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Autores> cbAutor;
    private javax.swing.JComboBox<Editoras> cbEditora;
    private javax.swing.JComboBox<Generos> cbGenero;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbCodLivro;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbPaginas;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelCb;
    private javax.swing.JPanel panelTf;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfCodLivro;
    private javax.swing.JTextField tfISBN;
    private javax.swing.JTextField tfPaginas;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
